openapi: '3.0.3'
info:
  title: Cat Fact API
  version: 1.0.0
servers:
  - url: https://catfact.ninja
    description: Cat Fact API server
paths:
  /fact:
    get:
      operationId: getFact
      responses:
        '200':
          description: A success response with a cat fact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fact'
  /:
    get:
      operationId: getAge
      parameters:
      - name: name
        required: true
        in: query
        description: The name used to guess users age
        schema:
          type: string
      responses:
        '200':
          description: A succed response with age
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Age'
components:
  schemas:
    Fact:
      type: object
      properties:
        fact:
          type: string
        length:
          type: integer
    Age:
      type: object
      properties:
        count:
          type: integer
        name:
          type: string
        age:
          type: integer
      
